[package]
name = "mat_calc"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mat = { path = "../" }
mat_macro = { path = "../mat_macro" }
indoc = "*"
